Добавлены микросетки на флексах для всех страниц
htmlacademy-htmlcss/797607-sedona-34 pull request #5
Opened 2022-06-29 09:42 UTC by AlexStetskij

2022-06-29 16:58 UTC, mikhin commented
@AlexStetskij , давай уберем эту надпись?

  <p>Репозиторий создан для обучения на профессиональном онлайн‑курсе «<a
      href="https://htmlacademy.ru/intensive/htmlcss">HTML и CSS. Профессиональная вёрстка сайтов</a>».</p>

2022-06-29 17:05 UTC, mikhin requested changes

2022-06-29 17:05 UTC, mikhin commented on catalog.html
> +            Кнопка хочу сюда!
Зачем слово "Кнопка"?

2022-06-29 17:05 UTC, mikhin commented on catalog.html
> +          <span class="house-icon"></span>
Не должны хотеть делать декоративные элементы через элементы-пустышки в HTML. Потому что разметка не должна страдать от стилизации. Лучше сделать это через псевдо-элементы в CSS.

https://developer.mozilla.org/ru/docs/Web/CSS/Pseudo-elements

2022-06-29 17:05 UTC, mikhin commented on catalog.html
> +              </label><label class="control-price">
Лейбл не должен быть пустым.

2022-06-29 17:05 UTC, mikhin commented on catalog.html
> +                <button class="price-slider-button" type=""></button>
Давай добавим какой-то текст, потому что все интерактивные элементы должны иметь какие-то текстовые подписи. Если визуально текст не нужен, его можно скрыть через стили.

2022-06-29 17:05 UTC, mikhin commented on catalog.html
> +          <label for="newsletter-email" hidden>Ваш Email</label>
`hidden` жестко вырубает контент для всех видов юзер-агентов, даже для электронных читалок, а это не то, что мы тут должны хотеть.

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/hidden

Тут нужна техника visually hidden.

https://htmlacademy.ru/blog/useful/html/short-12

2022-06-29 17:05 UTC, mikhin commented on styles/styles.css
> +.visually-hidden {
Во, да, вот этот класс прям бахать нужно в разметке там, где ты хочешь что-то скрыть чисто визуально.

2022-06-29 17:05 UTC, mikhin commented on styles/styles.css
> +  top: 35;
наверно нужно пиксели указать?

2022-06-29 17:05 UTC, mikhin commented on styles/styles.css
> +.main-image::before {
Для чего этот элемент?

2022-07-11 09:20 UTC, AlexStetskij commented
Все пофикшено следующем пулреквесте

2022-07-11 09:21 UTC, merged